FROM ubuntu:latest

COPY .docker/entrypoint.sh /entrypoint.sh
RUN apt-get update \
  && apt-get install -y \
    tzdata vim curl wget git \
    python3-venv \
  && rm -rf /var/lib/apt/lists/*

RUN curl -s https://get.modular.com | sh - \
  && modular install mojo \
  && python3 -m venv /opt/mojo/venv \
  && rm -rf /var/lib/apt/lists/* \
  && chmod +x /entrypoint.sh

ARG MODULAR_HOME="/root/.modular"
ENV MODULAR_HOME=$MODULAR_HOME
ENV PATH="$PATH:$MODULAR_HOME/pkg/packages.modular.com_mojo/bin"

ENTRYPOINT ["/entrypoint.sh"]
  